pull_request_rules:
  - name: automatically merge scala-steward's PRs
    conditions:
      - author=indoorvivants-steward[bot]
      - or:
        - body~=labels:.*semver-patch.*
        - body~=labels:.*semver-spec-patch.*
      - check-success=mergify-build-checkpoint
    actions:
      merge:
        method: merge
      delete_head_branch:
